Диплом Этап 1. Сервис статистики
elmuss/java-explore-with-me pull request #2
Opened 2024-11-11 19:17 UTC by elmuss

2024-11-19 13:00 UTC, VadimZharkov commented on stats/pom.xml
> +    <dependencies>
Зависимости лучше поместить в дочерние модули, т.к. для разных модулей pom будут разные. Например, для клиента spring-boot-starter-data-jpa, spring-boot-starter-actuator и постгес не нужны, а в текущей реализации они подтянутся, в результате в jar будет масса не нужных зависимостей.

2024-11-19 13:07 UTC, VadimZharkov commented on stats/stats-server/src/main/java/org/example/controller/StatsController.java
> +    public List<StatsViewDto> getHits(@Valid @RequestParam String start,
`@Valid` здесь лишнее (не понятно что хотели отвалидировать)

2024-11-19 13:12 UTC, VadimZharkov requested changes
Хорошая работа, можно улучшить

2024-11-19 17:13 UTC, elmuss commented
Привет, спасибо за проверку! Поправила по замечаниям.

2024-11-20 05:55 UTC, VadimZharkov approved these changes

2024-11-20 16:55 UTC, merged